### ISSUE TITLE
Codable support?

### ISSUE THREAD

**Issue by ingun37** [objecthub/swift-numberkit#11]
Could you make it `Codable`? 
(`Codable` is Swift standard protocol for encoding/decoding. [Doc](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types#overview))

**Comment by objecthub** [comment]
Thanks for the proposal. This is indeed a useful extension. Have added support for `Codable` to all numeric datatypes of NumberKit.
