### ISSUE TITLE
FloatingPoint to Rational

### ISSUE THREAD

**Issue by thelonious** [objecthub/swift-numberkit#12]
Is there an initializer or method to convert floats and doubles to rationals? I ended up writing my own conversions to Rational<BigInt>, but I wanted to check if I'm overlooking already existing support for that.

**Comment by objecthub** [comment]
Good point! I've added a new constructor to `Rational` which approximates a given `Double` up to a given precision.

**Comment by thelonious** [comment]
That's an interesting implementation. Thanks for adding that!
