### ISSUE TITLE
'StaticBigInt' is only available in iOS 16.4 or newer

### ISSUE THREAD

**Issue by iOSAnkit** [objecthub/swift-numberkit#20]
I am using hedera-swift-sdk which has dependency on numberkit library after updating the library I am getting this below error :-
Not able to compile the code with swift-numberkit version 2.5.0 
'StaticBigInt' is only available in iOS 16.4 or newer
extension BigInt - line number: 1208

<img width="723" alt="Screenshot 2024-04-17 at 11 08 42 AM" src="https://github.com/objecthub/swift-numberkit/assets/24468775/34925628-377c-46d1-843b-40d828c8fbd6">

**Comment by objecthub** [comment]
I found a way to use `StaticBigInt` conditionally. Have removed the new platform requirements and prepared a new release. Can you please verify that your problem is solved with version 2.5.1 of swift-numberkit?

**Comment by iOSAnkit** [comment]
Thanks @objecthub the latest release 2.5.1 is working for me.
