### ISSUE TITLE
Question: Are you interested in making one of the internal initializers public?

### ISSUE THREAD

**Issue by RLovelett** [objecthub/swift-numberkit#9]
I was wondering what stomach you might have for making [one of the initializers](https://github.com/objecthub/swift-numberkit/blob/ea87ff4d6074ccb2eb595bffc357892f2e170775/Sources/NumberKit/BigInt.swift#L128-L135) that is currently marked as `internal` as `public`. I was thinking of documenting the initializer and changing the access scope to `public` and submitting a PR. I wanted to check to see if that was something you were willing to entertain before I spent the time.

I'm writing a DER/BER encoder/decoder and your `BigInt` implementation is a great solution for storing and displaying arbitrary length integers. In fact, for the most part your `init` I linked above is _almost exactly_ what is encoded in the format. If I parse and send it to that `init` I get the integer I was expecting.

**Comment by objecthub** [comment]
I didn't see a use case for the constructor so I declared it `internal`. Since the constructor is totally safe to use and does the required normalisations, all what's needed is some documentation to make it `public`. Just send me a PR.
